# Generated by Django 3.1.4 on 2020-12-11 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV')], max_length=10)),
                ('car_name', models.CharField(max_length=30)),
                ('languages_known', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada')], max_length=30)),
                ('available_city', models.CharField(max_length=30)),
                ('price_per_km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_city', models.CharField(max_length=30)),
                ('destination_city', models.CharField(max_length=30)),
                ('depart_date_time', models.DateTimeField()),
                ('return_date_time', models.DateTimeField(null=True)),
                ('pickup_address', models.TextField(null=True)),
                ('pickup_time', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.drivers')),
            ],
        ),
    ]
